# Generated by Django 3.2.7 on 2021-09-16 19:57

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(null=True, validators=[users.validators.MinAgeValidator]),
        ),
    ]
