# Generated by Django 3.2.7 on 2021-09-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Node',
        ),
    ]
