# Generated by Django 3.2.7 on 2021-09-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_auto_20210917_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='content',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='content'),
        ),
    ]
