# Generated by Django 3.2.7 on 2021-09-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0005_alter_node_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='content'),
        ),
    ]
